-- 테이블 생성
CREATE TABLE AUTH_NAMES
(
  AUTH_NAME VARCHAR(200) NULL     COMMENT '접근권한명',
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '접근권한 대표값',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '접근권한명';

CREATE TABLE AUTHS
(
  UNIQUE_ID           VARCHAR(200) NOT NULL COMMENT '대표값',
  UNIQUE_ID_AUTH_NAME VARCHAR(200) NOT NULL COMMENT '접근권한 대표값'
) COMMENT '권한들';

CREATE TABLE USERS
(
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '대표값',
  USERS_NAME VARCHAR(200) NULL     COMMENT '이름',
  E_MAIL    VARCHAR(200) NULL     COMMENT '이메일',
  JOB       VARCHAR(200) NULL     COMMENT '직책',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '사용자들';

ALTER TABLE AUTHS
  ADD CONSTRAINT FK_USERS_TO_AUTHS
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES USERS (UNIQUE_ID);

ALTER TABLE AUTHS
  ADD CONSTRAINT FK_AUTH_NAMES_TO_AUTHS
    FOREIGN KEY (UNIQUE_ID_AUTH_NAME)
    REFERENCES AUTH_NAMES (UNIQUE_ID);

-- 데이터 입력
INSERT INTO auth_names (AUTH_NAME, UNIQUE_ID)
VALUES ('GUEST', 'B1');

INSERT INTO auth_names (AUTH_NAME, UNIQUE_ID)
VALUES ('ADMIN', 'B2');

INSERT INTO auth_names (AUTH_NAME, UNIQUE_ID)
VALUES ('MANAGER', 'B3');

-- 회원 가입
INSERT INTO users (UNIQUE_ID, USERS_NAME, E_MAIL, JOB)
VALUES ('U1', 'Paul', 'paul01@gmail.com', 'IT Billing');

INSERT INTO users (UNIQUE_ID, USERS_NAME, E_MAIL, JOB)
VALUES ('U2', 'Allen', ' texas@imfblog.org', 'Engineering');

INSERT INTO users (UNIQUE_ID, USERS_NAME, E_MAIL, JOB)
VALUES ('U3', 'Teddy', 'norway@iotm.com', 'IT Billing');

INSERT INTO users (UNIQUE_ID, USERS_NAME, E_MAIL, JOB)
VALUES ('U4', 'Paul', 'paul_p@naver.com', 'IT Billing');

-- auths
INSERT INTO auths (UNIQUE_ID, UNIQUE_ID_AUTH_NAME)
VALUES ('U1', 'B1');

INSERT INTO auths (UNIQUE_ID, UNIQUE_ID_AUTH_NAME)
VALUES ('U1', 'B2');

INSERT INTO auths (UNIQUE_ID, UNIQUE_ID_AUTH_NAME)
VALUES ('U2', 'B1');

INSERT INTO auths (UNIQUE_ID, UNIQUE_ID_AUTH_NAME)
VALUES ('U2', 'B2');

INSERT INTO auths (UNIQUE_ID, UNIQUE_ID_AUTH_NAME)
VALUES ('U2', 'B3');

INSERT INTO auths (UNIQUE_ID, UNIQUE_ID_AUTH_NAME)
VALUES ('U3', 'B1');

INSERT INTO auths (UNIQUE_ID, UNIQUE_ID_AUTH_NAME)
VALUES ('U4', 'B2');

INSERT INTO auths (UNIQUE_ID, UNIQUE_ID_AUTH_NAME)
VALUES ('U4', 'B1');

-- 회원 탈퇴
DELETE FROM auths
WHERE UNIQUE_ID = 'U2';

DELETE FROM auths
WHERE UNIQUE_ID = 'U4';

DELETE FROM users
WHERE UNIQUE_ID = 'U2';

DELETE FROM users
WHERE UNIQUE_ID = 'U4';

SELECT *
FROM auth_names;

SELECT *
FROM auths;

SELECT *
FROM users;